server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          node: worker
          instance: '${HOSTNAME}'
          application: policykit
          environment: development
          __path__: /var/log/nginx/*log
  - job_name: supervisor
    static_configs:
      - targets:
          - localhost
        labels:
          node: worker
          job: supervisor
          instance: '${HOSTNAME}'
          application: policykit
          environment: development
          __path__: /var/log/supervisor/*log
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          node: worker
          instance: '${HOSTNAME}'
          application: policykit
          __path__: /var/log/*log
          environment: development
  - job_name: docker
    pipeline_stages:
      - docker: { }
    static_configs:
      - labels:
          job: docker
          node: worker
          instance: '${HOSTNAME}'
          application: policykit
          environment: development
          __path__: /var/lib/docker/containers/*/*-json.log