alerting:
  alertmanagers:
    - static_configs:
        - targets: null
global:
  evaluation_interval: 30s
  scrape_timeout: 10s
  scrape_interval: 30s
rule_files: null
scrape_configs:
  - job_name: policykit-node-exporter
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - node_exporter:9100

  - job_name: policykit-docker-exporter
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - cadvisor:8080
